### PR TITLE
docs(samples): adds samples from documentation with correct region tags

### LINKED ISSUE #369: Add samples from documentation
Samples exist in the Data Catalog documentation on cloud.google.com that are not present here. These samples should be added to improve their discoverability and ensure consistency across the library and the docs.

### PR DESCRIPTION
**Pull request by pmakani**
Fixes #369

### CODE REVIEW

**Comment by pmakani** [comment]
@googlebot I consent.

**Comment by pmakani** [comment]
@googlebot I consent

**Comment by eaball35** [comment]
Screen Shot 2020-12-17 at 8 59 36 AM
Screen Shot 2020-12-17 at 8 59 57 AM

**Review by eaball35 — CHANGES_REQUESTED** [review]
blocking checks

**Comment by eaball35** [comment]
Should we close this?

**Comment by meredithslota** [comment]
@stephaniewang526 There are a few test failures here - I am not certain if this is because of the Data Catalog service issues @shollyman is working on resolving, or if there is something else. Can you PTAL?

**Review by stephaniewang526 — APPROVED** [review]

**Pull request merged**
